name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install SDL2
      run: sudo apt-get install -y libsdl2-dev
    - name: make
      run: make
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.0.0
      
